### ISSUE TITLE
[BUG]: It mints on testnet

### ISSUE THREAD

**Issue by dotdotdev** [AnishDe12020/twnft#3]
### Description of the bug

it mints nft on testnet.
why It doesnot mint on the real production network of opensea?

### Steps To Reproduce

mint nft

**Comment by AnishDe12020** [comment]
It mints on the testnet as the smart contract has been deployed on the testnet. It is not a bug.

I just put up a message notifying the users about this behavior

**Comment by dotdotdev** [comment]
sounds good but i think you have claimed that it mints free and you bear the cost, which is quite deviating from the fact that it mints on testnet which is why its already free.
